classdef MaxPooling2DHostStrategy < nnet.internal.cnn.layer.util.ExecutionStrategy
    % MaxPooling2DHostStrategy   Execution strategy for running the max pooling on the host
    
    %   Copyright 2016 The MathWorks, Inc.
    
    methods
        function [Z, memory] = forward(~, X, ...
                poolHeight, poolWidth, ...
                verticalPad, horizontalPad, ...
                verticalStride, horizontalStride)
            Z = nnet.internal.cnnhost.poolingMaxForward2D(X, ...
                poolHeight, poolWidth, ...
                verticalPad, horizontalPad, ...
                verticalStride, horizontalStride);
            memory = [];
        end
    end
end